---
title: "Install/Update R & RStudio"
output: 
  html_document: 
    fig_caption: yes
    toc: yes
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Before the first session
To participate in the Data Science Essentials in R series, please bring a laptop with R and RStudio installed.  We recommend that you have the latest version of R (4.0.3 Bunny-Wunnies Freak Out) and of the tidyverse package (1.3.0).  You need to have RStudio installed, but it is less crucial that you are using the most recent version (1.4.1103). 

Do you already have R and RStudio installed? 

* No - follow the instructions for ["I do not have R installed"](#noinstall)
* Yes - follow the instructions for ["I have R installed"](#yesinstall)


# "I do not have R installed" {#noinstall}
You should install R, RStudio, and tidyverse. 

## Installing R
 
### Windows:

1. Go to<https://cloud.r-project.org/bin/windows/base/>
2. Click the "Download R 4.0.3 for Windows" link.
3. When the file finishes downloading, double-click to install. You should be able to click "Next" to all dialogs to finish the installation.
 
### Mac:

1. Go to <https://cloud.r-project.org/bin/macosx/>
2. Click the link "R-4.0.3.pkg"
3. When the file finishes downloading, double-click to install. You should be able to click "Next" to all dialogs to finish the installation.
 
 
## Installing RStudio 
 
1. Go to <https://www.rstudio.com/products/rstudio/download/#download>. 
2. Under "Installers for Supported Platforms" select the appropriate installer for your operating system.
3. When the file finishes downloading, double-click to install. You should be able to click "Next" to all dialogs to finish the installation.

## Installing tidyverse {#installtidyverse}
Open RStudio.  Go to Tools (at top)...Install Packages.  Enter `tidyverse`, then select Install. 

You are ready for Data Science Essentials for R!

# "I have R installed" {#yesinstall}
The workshops run more smoothly when everyone is using the same version of R and tidyverse. Please update R and tidyverse, if necessary (and less crucially, RStudio). 

## Verify R version
Open RStudio.  At the top of the Console you will see session info.  The first line tells you which version of R you are using. If RStudio is already open and you're deep in a session, type `R.version.string` to print out the R version.

Do you have R version 4.0.3 ("Bunny-Wunnies Freak Out") installed?

* No - follow the instructions for ["Updating R"](#updateR) 
* Yes - Great!  Do you have tidyverse installed?
    + No or I don't know - See ["Installing tidyverse"](#installtidyverse)
    + Yes - Great! Go to Go to Tools (at top)...Check for Package Updates. If there's an update available for tidyverse, install it.
    
You are ready for Data Science Essentials for R!
    

## Updating R/RStudio/Tidyverse {#updateR}
### Windows 

To update R on Windows, try using the package [`installr`](https://cran.r-project.org/web/packages/installr/index.html) (only for Windows)

1. Install and load `installr`: `install.packages("installr")` and `library(installr)`
2. Call `updateR()` function. This will start the updating process of your R installation by: "finding the latest R version, downloading it, running the installer, deleting the installation file, copy and updating old packages to the new R installation."
3. From within RStudio, go to Help (at top)...Check for Updates to install newer version of RStudio (if available, optional).

You are ready for Data Science Essentials for R!

### Mac

On Mac, you can simply download and install the newest version of R. When you restart RStudio, it will use the updated version of R.

1. Go to <https://cloud.r-project.org/bin/macosx/>
2. Click the link "R-4.0.3.pkg"
3. When the file finishes downloading, double-click to install. You should be able to click "Next" to all dialogs to finish the installation.
4. From within RStudio, go to Help > Check for Updates to install newer version of RStudio (if available, optional).
5. To update packages, go to Tools > Check for Package Updates. If updates are available, select All (or just tidyverse), and click Install Updates.

You are ready for Data Science Essentials for R!

